I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 81, in script
    jump hobby
ScriptError: could not find label 'hobby'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 81, in script
    jump hobby
  File "/Users/phong/Documents/renpy-8.2.3-sdk/renpy/ast.py", line 1701, in execute
    rv = renpy.game.script.lookup(target)
  File "/Users/phong/Documents/renpy-8.2.3-sdk/renpy/script.py", line 1103, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'hobby'.

macOS-10.16-x86_64-i386-64bit x86_64
Ren'Py 8.2.3.24061702
Les Forceurs de l'Espace 1.0
Fri Aug 16 14:49:38 2024
