I'm sorry, but an uncaught exception occurred.

While running game code:
  File "renpy/common/00images.rpy", line 55, in script
    init python:
  File "renpy/common/00images.rpy", line 58, in <module>
    _scan_images_directory()
  File "renpy/common/00images.rpy", line 53, in _scan_images_directory
    renpy.image(base, fn)
Exception: Unknown image modifier '2x' in 'images/steakguez_frame@2x.webp'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "renpy/common/00images.rpy", line 55, in script
    init python:
  File "C:\Users\vuong\Documents\renpy-8.2.3-sdk\renpy\ast.py", line 823, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\vuong\Documents\renpy-8.2.3-sdk\renpy\python.py", line 1178, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "renpy/common/00images.rpy", line 58, in <module>
    _scan_images_directory()
  File "renpy/common/00images.rpy", line 53, in _scan_images_directory
    renpy.image(base, fn)
  File "C:\Users\vuong\Documents\renpy-8.2.3-sdk\renpy\exports.py", line 341, in image
    d = renpy.easy.displayable(d)
  File "C:\Users\vuong\Documents\renpy-8.2.3-sdk\renpy\easy.py", line 128, in displayable
    return renpy.store.Image(d)
  File "C:\Users\vuong\Documents\renpy-8.2.3-sdk\renpy\display\im.py", line 2013, in image
    return Image(arg, **properties)
  File "C:\Users\vuong\Documents\renpy-8.2.3-sdk\renpy\display\im.py", line 697, in __init__
    raise Exception("Unknown image modifier %r in %r." % (i, filename))
Exception: Unknown image modifier '2x' in 'images/steakguez_frame@2x.webp'.

Windows-10-10.0.22631 AMD64
Ren'Py 8.2.3.24061702
Virtual LilySon 1.0
Mon Aug 19 00:48:15 2024
